{% set data = load_setup_py_data() %}

package:
  name: "hydrophobicity_explorer"
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - python >=3.6

  run:
    - python >=3.6
    - pandas
    - scipy
    - matplotlib-base
    - rdkit
    - tqdm

build:
  script: python3 setup.py install
  noarch: python
  number: 1
  entry_points:
    - makePol = hydrophobicity_explorer.MakePolymer:main
    - customPol = hydrophobicity_explorer.custom_input_to_mol_file:main
    - HXSettings = hydrophobicity_explorer.settings:main
    - HXNB = hydrophobicity_explorer.nb:main
    - HXLib = hydrophobicity_explorer.smiles:main

test:
  imports:
    - rdkit
    - scipy
    - hydrophobicity_explorer
    - pandas
    - matplotlib
    - tqdm

  commands:
    - makePol -h
    - customPol -h
    - HXSettings -h
    - HXSettings -s
    - HXLib -h
    - HXLib -e
    - HXLib -m

# requirements:
#   build:
#     - setuptools
#     - python
#     - pandas
#     - scipy
#     - matplotlib
#     - rdkit

#   host:
#     - python

# build:  
#   preserve_egg_dir: True
