{% set data = load_setup_py_data() %}

package:
  name: "hydrophobicity_explorer"
  version: {{ data.get('version') }}

source:
  url: https://files.pythonhosted.org/packages/49/04/34ed391a2e98a59b26f9f1f9861cc678329494293fd28faf2c2387e70df8/hydrophobicity_explorer-0.1.3.4.tar.gz
  md5: fa2776cf1ad09d834ee053383ff0409e


build:
  #noarch: python
  number: 0
  entry_points:
    - makePol = hydrophobicity_explorer.MakePolymer:main
    - customPol = hydrophobicity_explorer.custom_input_to_mol_file:main
    - HXSettings = hydrophobicity_explorer.settings:main
    - HXNB = hydrophobicity_explorer.nb:main
    - HXLib = hydrophobicity_explorer.smiles:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - matplotlib-base
    - pandas
    - python
    - rdkit
    - scipy
    - rich
  run:
    - matplotlib-base
    - pandas
    - python
    - rdkit
    - scipy
    - rich

test:
  imports:
    - hydrophobicity_explorer
  commands:
    - makePol -h
    - customPol -h
    - HXSettings -h
    - HXSettings -s
    - HXLib -h
    - HXLib -e
    - HXLib -m

about:
  home: "https://github.com/TheHydrophobicityProject/HydrophobicityExplorer"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "../license.txt"
  summary: "Facilitates solubility calculations on a wide range of polymers."

# build:
#   script: python3 setup.py install
#   noarch: python
#   number: 1
