{% set data = load_setup_py_data() %}

package:
  name: "hydrophobicity_explorer"
  version: {{ data.get('version') }}

source:
  url: https://files.pythonhosted.org/packages/cb/6d/3e2da9380633376e83d533554ca962eb3c6c1cc70c4e70bf4ccfc879ea77/mhp-0.1.3.4.tar.gz
  md5: 3d6a1b44e08849839a2f9a6cd591231f

build:
  noarch: python
  number: 3
  entry_points:
    - makePol = hydrophobicity_explorer.MakePolymer:main
    - customPol = hydrophobicity_explorer.custom_input_to_mol_file:main
    - HXSettings = hydrophobicity_explorer.settings:main
    - HXNB = hydrophobicity_explorer.nb:main
    - HXLib = hydrophobicity_explorer.smiles:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - matplotlib-base
    - pandas
    - python
    - rdkit
    - scipy
  run:
    - matplotlib-base
    - pandas
    - python
    - rdkit
    - scipy

test:
  imports:
    - hydrophobicity_explorer
  commands:
    - makePol -h
    - customPol -h
    - HXSettings -h
    - HXSettings -s
    - HXLib -h
    - HXLib -e
    - HXLib -m

about:
  home: "https://github.com/TheHydrophobicityProject/HydrophobicityExplorer"
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: "../license.txt"
  summary: "Facilitates solubility calculations on a wide range of polymers."

# build:
#   script: python3 setup.py install
#   noarch: python
#   number: 1


